#Download base Ubuntu base image
FROM Ubuntu 
MAINTAINER Saravanan Sekar

#Run software update
RUN apt-get update

#Get latest python
RUN apt-get install -y python3.6

#Copy shell script
COPY print.sh /print.sh

#run command
ENTRYPOINT /print.sh


