#Download base Ubuntu base image
FROM python:3 
MAINTAINER Saravanan Sekar

#Run software update
#RUN apt-get update

#Get latest python
#RUN apt-get install -y python3.6

#RUN mkdir app

#Adding to Path
#ENV PYTHONPATH ${PATH}:/app

#Copy shell script
#COPY print.sh /print.sh

#run command
#ENTRYPOINT /print.sh

CMD "python3"